### ISSUE TITLE
Error with useListItems and useSite Hooks in SPFx 1.20.0

### ISSUE THREAD

**Issue by Sandeep-FED** [SuperioOne/pnp-react-hooks#2]
I’m encountering an issue with the useListItems and useSite hooks after upgrading to SPFx version 1.20.0. These hooks were functioning correctly in the previous release, but I receive the following error message:

`Module not found: Error: Invalid "exports" target "dist/index.js" defined for "." in the package config C:\Users\SandeepPS\Desktop\upgrade-samples\sp-dev-fx-webparts\samples\react-modern-carousel\node_modules\pnp-react-hooks\package.json, targets must start with "./"
`

**Environment**

- SPFx Version: 1.20.0
- Node Version: 18.18.2
- @pnp/sp Version: 4.6.0

**Steps to Reproduce**
- Upgrade the SPFx version to 1.20.0.
- Attempt to use the useListItems and useSite hooks in the application.
- Observe the error in the console.

**Pull Request**
@SuperioOne , I have created a pull request to fix this issue, which updates the exports target in the pnp-react-hooks/package.json. The changes have been tested in my environment, and everything is functioning as expected now.

**Additional Context**
Please review the PR linked below and merge it if everything looks good:
[Link to PR](https://github.com/SuperioOne/pnp-react-hooks/pull/1)

**Comment by SuperioOne** [comment]
Thanks for the PR! It has been released as `v2.0.1`.
